spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:lko
    username: sa
    password:
  jpa:
    properties:
      hibernate.show_sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: false
server:
  port: 8082